# Generated by Django 6.1.2 on 2026-10-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("standard", "Standard Delivery"),
                            ("express", "Express Delivery"),
                            ("in_house", "In-house Delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estimated_days",
                    models.CharField(
                        blank=True, help_text="e.g. 2-5 business days", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
