# Generated by Django 6.1.2 on 2026-10-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(default="WebVault Fashion Store", max_length=200),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#4F46E5",
                        help_text="Hex code e.g. #4F46E5",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#1E293B",
                        help_text="Hex code e.g. #1E293B",
                        max_length=7,
                    ),
                ),
                (
                    "hero_text",
                    models.CharField(
                        default="Elegance in Every Stitch", max_length=200
                    ),
                ),
                (
                    "hero_banner",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("about_us", models.TextField(blank=True)),
                (
                    "contact_email",
                    models.EmailField(default="hello@example.com", max_length=254),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "default_delivery_fee",
                    models.DecimalField(
                        decimal_places=2, default=3000.0, max_digits=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
    ]
