# Generated by Django 6.1.2 on 2026-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="active_gateway",
            field=models.CharField(
                choices=[
                    ("paystack", "Paystack"),
                    ("flutterwave", "Flutterwave"),
                    ("monnify", "Monnify"),
                    ("squad", "Squad"),
                    ("none", "No Online Payment (Cash/Transfer only)"),
                ],
                default="paystack",
                help_text="Which payment gateway to use at checkout",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="flutterwave_public_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="flutterwave_secret_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="monnify_api_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="monnify_contract_code",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="monnify_secret_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="paystack_public_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="paystack_secret_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="squad_public_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="squad_secret_key",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
