"""
Django settings for fashion_store project.

Generated by 'django-admin startproject' using Django 6.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-0vihpxuvaz%ap!1l^+4g$oz=x0rz0-ga(ymza7-kmopsos=fi5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow Codespaces and local development
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.app.github.dev',
    'https://*.githubpreview.dev',
    'http://localhost:8000',
    'https://localhost:8000',      # <--- ADD THIS
    'http://127.0.0.1:8000',
    'https://127.0.0.1:8000',      # <--- ADD THIS
]
# Application definition

INSTALLED_APPS = [
    'jazzmin',  # <-- Add Jazzmin here (must be above admin)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # WebVault Apps
    'core',
    'products',
    'orders',
    'payments',
    'delivery',
    'accounts',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fashion_store.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.store_settings', # <--- MAKE SURE THIS IS HERE
                'orders.context_processors.cart_counter', # <--- Add this
            ],
        },
    },
]

WSGI_APPLICATION = "fashion_store.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded logos, product images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

# ─────────────────────────────────────────
# JAZZMIN CONFIGURATION
# ─────────────────────────────────────────
JAZZMIN_SETTINGS = {
    "show_ui_builder": False,
    "custom_css": "css/admin_custom.css",   # <-- Add this line
    "site_title": "WebVault Admin",
    "site_header": "WebVault",
    "site_brand": "WebVault Fashion",
    "welcome_sign": "Welcome to your store dashboard",
    "copyright": "WebVault",
    "search_model": ["auth.User", "orders.Order"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Visit Store", "url": "/", "new_window": True},
    ],
    "show_ui_builder": False,   # <-- Change to False
    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
    "navigation_expanded": True, # <-- Sidebar opens by default
    "hide_apps": [],              # <-- Apps to hide from sidebar
    "hide_models": [],            # <-- Models to hide
    "order_with_respect_to": [    # <-- Order the sidebar
        "orders",
        "products",
        "delivery",
        "core",
        "auth",
    ],
} 

# ─────────────────────────────────────────
# EMAIL CONFIGURATION (Django 6.1+)
# ─────────────────────────────────────────
import os

# Development default: print emails to the console.
# In production, the buyer sets EMAIL_HOST, EMAIL_HOST_USER, and EMAIL_HOST_PASSWORD
# as environment variables on their hosting platform (Railway, Render, etc.).
_email_host = os.environ.get('EMAIL_HOST', '')

if _email_host:
    # Production mode — use SMTP
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": _email_host,
                "port": int(os.environ.get('EMAIL_PORT', 587)),
                "use_tls": os.environ.get('EMAIL_USE_TLS', 'True') == 'True',
                "username": os.environ.get('EMAIL_HOST_USER', ''),
                "password": os.environ.get('EMAIL_HOST_PASSWORD', ''),
            },
        },
    }
else:
    # Development mode — print emails to the console (no real sending)
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.console.EmailBackend",
        },
    }

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@webvault.store')
